name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image locally
      run: docker build . --file Dockerfile --tag yahoo_scraper:latest
    - name: Login to Docker
      run: >
        docker login
        -u ${{ secrets.DOCKER_HUB_USERNAME }}
        -p ${{ secrets.DOCKER__HUB_ACCESS_TOKEN }}
    - name: Push Docker image to hub
      run: docker push yahoo_scraper:latest